name: flutter_snowboy
description: A Flutter plugin for Snowboy hotword detection
version: 0.0.1
author: Sveinbjorn Thordarson (Miðeind ehf.)
homepage: https://github.com/mideind/flutter_snowboy

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: is.mideind.flutter_snowboy
        pluginClass: FlutterSnowboyPlugin
